FROM node:8.11

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV NODE_ENV development

RUN yarn global add typescript
COPY package.json /usr/src/app
RUN yarn install
COPY . /usr/src/app

RUN mkdir -p /usr/src/app/server/ && chmod -R 777 /usr/src/app/server/
RUN touch /usr/src/app/server/sre-webapp.log && chmod 777 /usr/src/app/server/sre-webapp.log
RUN chmod -R 777 /usr/src/app

EXPOSE 8000
CMD ["yarn", "start"]
